"""Anki adapter backed by AnkiOpsConnect with AnkiConnect fallback."""

import logging
import shutil
from collections.abc import Callable
from pathlib import Path
from typing import Any, cast

from ankiops.anki_rpc import AnkiConnectionError, invoke
from ankiops.media_paths import validate_local_media_path, validate_media_filename
from ankiops.note_types import ANKIOPS_KEY_FIELD, NoteType
from ankiops.notes import AnkiNote, normalize_tags
from ankiops.sync.report import Change

logger = logging.getLogger(__name__)

# Editor-side field properties (set through AnkiOpsConnect or AnkiConnect)
FIELD_FONT_SIZES = {
    "Source": 14,
    "AI Notes": 14,
    ANKIOPS_KEY_FIELD.name: 14,
}
FIELD_DESCRIPTIONS = {
    "AI Notes": "Auto-generated by AI — do not edit",
    ANKIOPS_KEY_FIELD.name: "Internal note_key for AnkiOps sync — do not edit",
}


def _action(action_str: str, **params) -> dict:
    return {"action": action_str, "params": params}


def _quote_search_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _quote_field_exact_search(field_name: str, value: str) -> str:
    escaped_field = field_name.replace("\\", "\\\\").replace('"', '\\"')
    escaped_value = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped_field}:{escaped_value}"'


def _normalize_model_styling_payload(styling: object, *, model_name: str) -> str:
    """Normalize modelStyling payloads to raw CSS text."""
    if isinstance(styling, str):
        return styling
    if isinstance(styling, dict):
        css = styling.get("css")
        if isinstance(css, str):
            return css
        raise AnkiConnectionError(
            "Malformed modelStyling response for "
            f"'{model_name}': expected dict with string 'css'."
        )
    raise AnkiConnectionError(
        "Malformed modelStyling response for "
        f"'{model_name}': expected string or dict with string 'css'."
    )


class Anki:
    """Adapter for Anki's local HTTP connection."""

    def __init__(self, invoke_func: Callable[..., Any] | None = None) -> None:
        self._invoke = invoke if invoke_func is None else invoke_func
        self._media_dir: Path | None = None

    def get_version(self) -> int:
        """Get the active Anki connection version."""
        return self._invoke("version")

    def get_active_profile(self) -> str:
        """Get the currently active Anki profile name."""
        return self._invoke("getActiveProfile")

    def fetch_deck_names_and_ids(self) -> dict[str, int]:
        return self._invoke("deckNamesAndIds")

    def fetch_card_ids_in_deck(self, deck_name: str) -> list[int]:
        return cast(
            list[int],
            self._invoke("findCards", query=f"deck:{_quote_search_value(deck_name)}"),
        )

    def delete_empty_deck(self, deck_name: str) -> None:
        """Delete a deck after the caller has verified it contains no cards."""
        self._invoke("deleteDecks", decks=[deck_name], cardsToo=True)

    def fetch_all_note_ids(self, required_types: list[str]) -> list[int]:
        if not required_types:
            return []
        query = " OR ".join(
            f"note:{_quote_search_value(model_name)}" for model_name in required_types
        )
        return self._invoke("findNotes", query=query)

    def fetch_note_ids_by_note_keys(self, note_keys: set[str]) -> dict[str, list[int]]:
        if not note_keys:
            return {}
        keys = sorted(note_keys)
        actions = [
            _action(
                "findNotes",
                query=_quote_field_exact_search(ANKIOPS_KEY_FIELD.name, note_key),
            )
            for note_key in keys
        ]
        results = self._invoke("multi", actions=actions)
        note_ids_by_key = {}
        for note_key, result in zip(keys, results):
            if isinstance(result, str):
                raise AnkiConnectionError(
                    f"Failed to search notes by AnkiOps Key '{note_key}': {result}"
                )
            note_ids_by_key[note_key] = list(result or [])
        return note_ids_by_key

    def fetch_cards_info(self, card_ids: list[int]) -> dict[int, dict]:
        if not card_ids:
            return {}
        cards = self._invoke("cardsInfo", cards=card_ids)
        return {card["cardId"]: card for card in cards if card}

    def fetch_notes_info(self, note_ids: list[int]) -> dict[int, AnkiNote]:
        if not note_ids:
            return {}
        notes = self._invoke("notesInfo", notes=note_ids)
        notes_by_id = {}
        for note_data in notes:
            if not note_data:
                continue
            fields = {name: data["value"] for name, data in note_data["fields"].items()}
            notes_by_id[note_data["noteId"]] = AnkiNote(
                note_id=note_data["noteId"],
                note_type=note_data.get("modelName", ""),
                fields=fields,
                card_ids=note_data.get("cards", []),
                tags=normalize_tags(note_data.get("tags", ())),
            )
        return notes_by_id

    # Models are Anki's note types
    def fetch_note_type_names(self) -> list[str]:
        return self._invoke("modelNames")

    def fetch_note_type_states(self, note_type_names: list[str]) -> dict[str, dict]:
        if not note_type_names:
            return {}
        read_actions = []
        for name in note_type_names:
            read_actions.append(_action("modelFieldNames", modelName=name))
            read_actions.append(_action("modelStyling", modelName=name))
            read_actions.append(_action("modelTemplates", modelName=name))
            read_actions.append(_action("modelFieldDescriptions", modelName=name))
            read_actions.append(_action("modelFieldFonts", modelName=name))

        read_results = self._invoke("multi", actions=read_actions)
        states = {}
        for model_index, name in enumerate(note_type_names):
            base = model_index * 5
            field_names = read_results[base]
            styling = _normalize_model_styling_payload(
                read_results[base + 1],
                model_name=name,
            )
            raw_desc = read_results[base + 3]
            descriptions = dict(zip(field_names, raw_desc))
            states[name] = {
                "fields": field_names,
                "styling": styling,
                "templates": read_results[base + 2],
                "descriptions": descriptions,
                "fonts": read_results[base + 4],
            }
        return states

    def create_note_types(self, note_types: list[NoteType]) -> None:
        if not note_types:
            return
        actions = []
        for model_config in note_types:
            fields = [field.name for field in model_config.fields]
            actions.append(
                _action(
                    "createModel",
                    modelName=model_config.name,
                    inOrderFields=fields,
                    css=model_config.css,
                    isCloze=model_config.is_cloze,
                    cardTemplates=model_config.templates,
                )
            )
            # Apply descriptions / fonts
            for field_name, desc in FIELD_DESCRIPTIONS.items():
                if field_name in fields:
                    actions.append(
                        _action(
                            "modelFieldSetDescription",
                            modelName=model_config.name,
                            fieldName=field_name,
                            description=desc,
                        )
                    )
            for field_name, size in FIELD_FONT_SIZES.items():
                if field_name in fields:
                    actions.append(
                        _action(
                            "modelFieldSetFontSize",
                            modelName=model_config.name,
                            fieldName=field_name,
                            fontSize=size,
                        )
                    )

        results = self._invoke("multi", actions=actions)
        errors = [
            result
            for result in results
            if result is not None and isinstance(result, str)
        ]
        if errors:
            raise AnkiConnectionError(f"Failed to create models: {errors}")

    def update_note_types(
        self, note_types: list[NoteType], states: dict[str, dict]
    ) -> None:
        if not note_types:
            return
        actions = []
        for model_config in note_types:
            state = states[model_config.name]
            expected_fields = [field.name for field in model_config.fields]
            current_fields = state["fields"]

            for field_name in expected_fields:
                if field_name not in current_fields:
                    actions.append(
                        _action(
                            "modelFieldAdd",
                            modelName=model_config.name,
                            fieldName=field_name,
                        )
                    )

            for field_name in current_fields:
                if field_name not in expected_fields:
                    actions.append(
                        _action(
                            "modelFieldRemove",
                            modelName=model_config.name,
                            fieldName=field_name,
                        )
                    )

            for field_index, field_name in enumerate(expected_fields):
                actions.append(
                    _action(
                        "modelFieldReposition",
                        modelName=model_config.name,
                        fieldName=field_name,
                        index=field_index,
                    )
                )

            actions.append(
                _action(
                    "updateModelStyling",
                    model={"name": model_config.name, "css": model_config.css},
                )
            )

            # Templates
            current_names = list(state["templates"].keys())
            for template_index, expected in enumerate(model_config.templates):
                if (
                    template_index < len(current_names)
                    and current_names[template_index] != expected["Name"]
                ):
                    actions.append(
                        _action(
                            "modelTemplateRename",
                            modelName=model_config.name,
                            oldTemplateName=current_names[template_index],
                            newTemplateName=expected["Name"],
                        )
                    )
                    current_names[template_index] = expected["Name"]

            templates_dict = {}
            for template_index, expected in enumerate(model_config.templates):
                if template_index < len(current_names):
                    templates_dict[current_names[template_index]] = {
                        "Front": expected["Front"],
                        "Back": expected["Back"],
                    }
                else:
                    actions.append(
                        _action(
                            "modelTemplateAdd",
                            modelName=model_config.name,
                            template=expected,
                        )
                    )

            if templates_dict:
                actions.append(
                    _action(
                        "updateModelTemplates",
                        model={"name": model_config.name, "templates": templates_dict},
                    )
                )

            # Descriptions and Fonts
            current_desc = state["descriptions"]
            current_fonts = state["fonts"]

            for field_name, desc in FIELD_DESCRIPTIONS.items():
                if (
                    current_desc.get(field_name) != desc
                    and field_name in expected_fields
                ):
                    actions.append(
                        _action(
                            "modelFieldSetDescription",
                            modelName=model_config.name,
                            fieldName=field_name,
                            description=desc,
                        )
                    )

            for field_name, size in FIELD_FONT_SIZES.items():
                if (
                    current_fonts.get(field_name, {}).get("size") != size
                    and field_name in expected_fields
                ):
                    actions.append(
                        _action(
                            "modelFieldSetFontSize",
                            modelName=model_config.name,
                            fieldName=field_name,
                            fontSize=size,
                        )
                    )

        if actions:
            results = self._invoke("multi", actions=actions)
            errors = [
                result
                for result in results
                if result is not None and isinstance(result, str)
            ]
            if errors:
                raise AnkiConnectionError(f"Failed to update models: {errors}")

    def apply_note_changes(
        self,
        deck_name: str,
        needs_create_deck: bool,
        creates: list[Change],
        updates: list[Change],
        deletes: list[Change],
        cards_to_move: list[int],
    ) -> tuple[list[int | None], list[str]]:
        actions = []
        action_tags = []
        errors = []
        created_ids: list[int | None] = []
        create_deck_failed = False

        if needs_create_deck:
            actions.append(_action("createDeck", deck=deck_name))
            action_tags.append("create_deck")

        if cards_to_move:
            actions.append(
                _action("changeDeck", cards=sorted(set(cards_to_move)), deck=deck_name)
            )
            action_tags.append("change_deck")

        for update_change in updates:
            note_id = update_change.entity_id
            fields = update_change.context.get("html_fields", {})
            note_tags = normalize_tags(update_change.context.get("tags", ()))
            actions.append(
                _action(
                    "updateNote",
                    note={
                        "id": note_id,
                        "fields": fields,
                        "tags": list(note_tags),
                    },
                )
            )
            action_tags.append("update")

        if deletes:
            note_ids = [
                delete_change.entity_id
                for delete_change in deletes
                if delete_change.entity_id
            ]
            actions.append(_action("deleteNotes", notes=note_ids))
            action_tags.append("delete")

        if actions:
            try:
                results = self._invoke("multi", actions=actions)
                update_idx = 0
                for tag, action_result in zip(action_tags, results):
                    if tag == "update":
                        if isinstance(action_result, str):
                            errors.append(
                                "Update failed "
                                f"({updates[update_idx].entity_repr}): {action_result}"
                            )
                        update_idx += 1
                    elif tag == "create_deck":
                        if isinstance(action_result, str):
                            create_deck_failed = True
                            errors.append(f"Failed create_deck: {action_result}")
                    elif tag in ("change_deck", "delete"):
                        if isinstance(action_result, str):
                            errors.append(f"Failed {tag}: {action_result}")

            except AnkiConnectionError as error:
                errors.append(str(error))

        if creates:
            if create_deck_failed:
                for create_change in creates:
                    errors.append(
                        "Create failed "
                        f"({create_change.entity_repr}): deck create failed"
                    )
            else:
                create_ids, create_errors = self._create_notes_bulk(deck_name, creates)
                created_ids.extend(create_ids)
                errors.extend(create_errors)

        return created_ids, errors

    def _build_create_note_payload(self, deck_name: str, change: Change) -> dict:
        note = change.context.get("note")
        fields = dict(change.context.get("html_fields", {}))
        note_type = note.note_type if note else ""
        if "note_key" in change.context:
            fields[ANKIOPS_KEY_FIELD.name] = change.context["note_key"]
        return {
            "deckName": deck_name,
            "modelName": note_type,
            "fields": fields,
            "tags": list(note.tags) if note else [],
            "options": {"allowDuplicate": False},
        }

    def _collect_create_results(
        self, creates: list[Change], results: object
    ) -> tuple[list[int | None], list[str]]:
        created_ids: list[int | None] = []
        errors: list[str] = []

        if not isinstance(results, list):
            return [None] * len(creates), [
                f"Create failed: unexpected addNotes result: {results!r}"
            ]

        normalized = list(results)
        if len(normalized) < len(creates):
            normalized.extend([None] * (len(creates) - len(normalized)))

        for create_change, create_result in zip(creates, normalized):
            if isinstance(create_result, int):
                created_ids.append(create_result)
            else:
                created_ids.append(None)
                errors.append(
                    f"Create failed ({create_change.entity_repr}): {create_result}"
                )

        return created_ids, errors

    def _collect_can_add_errors(
        self, creates: list[Change], results: object
    ) -> list[str]:
        if not isinstance(results, list) or len(results) != len(creates):
            return []

        errors: list[str] = []
        for create_change, result in zip(creates, results):
            if not isinstance(result, dict) or result.get("canAdd") is not False:
                continue
            error = result.get("error") or "cannot create note"
            errors.append(f"Create failed ({create_change.entity_repr}): {error}")
        return errors

    def _create_notes_bulk(
        self, deck_name: str, creates: list[Change]
    ) -> tuple[list[int | None], list[str]]:
        notes = [
            self._build_create_note_payload(deck_name, create_change)
            for create_change in creates
        ]
        try:
            can_add_results = self._invoke("canAddNotesWithErrorDetail", notes=notes)
            can_add_errors = self._collect_can_add_errors(creates, can_add_results)
            if can_add_errors:
                return [None] * len(creates), can_add_errors
        except AnkiConnectionError:
            pass

        try:
            results = self._invoke("addNotes", notes=notes)
            return self._collect_create_results(creates, results)
        except AnkiConnectionError as error:
            return [None] * len(creates), [
                f"Create failed ({create_change.entity_repr}): {error}"
                for create_change in creates
            ]

    def find_notes_by_ankiops_note_key(self, note_key: str) -> list[int]:
        return self._invoke("findNotes", query=f'"{ANKIOPS_KEY_FIELD.name}:{note_key}"')

    def convert_notes_to_note_type(
        self,
        note_ids: list[int],
        old_note_type: str,
        new_note_type: str,
    ) -> None:
        self._invoke(
            "convertNotesToNoteType",
            noteIds=note_ids,
            oldNoteType=old_note_type,
            newNoteType=new_note_type,
        )

    def get_media_dir(self) -> Path:
        """Return Anki's collection.media directory, cached after first call."""
        cached = self._media_dir
        if cached is None:
            cached = Path(self._invoke("getMediaDirPath"))
            self._media_dir = cached
        return cached

    def _anki_media_path(self, filename: str) -> Path:
        safe_name = validate_media_filename(filename)
        media_dir = self.get_media_dir().resolve()
        target = media_dir / safe_name
        if target.is_symlink() or target.resolve().parent != media_dir:
            raise ValueError(
                f"Unsafe media filename '{filename}': symbolic links are not allowed."
            )
        return target

    def push_media(self, local_path: Path, remote_filename: str) -> None:
        safe_local = validate_local_media_path(local_path, remote_filename)
        shutil.copyfile(safe_local, self._anki_media_path(remote_filename))

    def pull_media(self, remote_filename: str, local_path: Path) -> bool:
        safe_local = validate_local_media_path(local_path, remote_filename)
        source = self._anki_media_path(remote_filename)
        if not source.exists():
            return False
        shutil.copyfile(source, safe_local)
        return True

    def delete_media_file(self, remote_filename: str) -> None:
        """Delete one AnkiOps-managed media file when no source references it."""
        self._anki_media_path(remote_filename).unlink(missing_ok=True)
